/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.controller.delete;
import com.doan.controller.edit;
import com.doan.dao.TaiKhoanDAO;
import com.doan.model.TaiKhoan;

import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class AccountForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AccountForm
     */
    
    DefaultTableModel model;
    
    public AccountForm() {
        initComponents();
        
        initComponents();
        
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.setNorthPane(null);        // Ẩn thanh tiêu đề
        }
        
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        listAccount.setModel(model);
        String[] columns = {"Mã Tài Khoản", "Tên Tài Khoản","Username", "Vai Trò", "Trạng Thái"};
        model.setColumnIdentifiers(columns);

        List<TaiKhoan> list = new TaiKhoanDAO().getInstance().selectAll();
        for (TaiKhoan x : list) {
            model.addRow(new Object[]{
                x.getMaTK(), 
                x.getTenTK(), 
                x.getUsername(), 
                x.getRole(), 
                x.getStatus()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDelete = new javax.swing.JButton();
        changePasswordBtn = new javax.swing.JButton();
        changeStatusBtn = new javax.swing.JButton();
        changeRole = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAccount = new javax.swing.JTable();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chỉnh Sửa"));
        jToolBar1.setRollover(true);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/delete.png"))); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        changePasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/changePassword2.png"))); // NOI18N
        changePasswordBtn.setText("Đổi Mật Khẩu");
        changePasswordBtn.setFocusable(false);
        changePasswordBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changePasswordBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        changePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(changePasswordBtn);

        changeStatusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/changeStatus.png"))); // NOI18N
        changeStatusBtn.setText("Đổi Trạng Thái");
        changeStatusBtn.setFocusable(false);
        changeStatusBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changeStatusBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        changeStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStatusBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(changeStatusBtn);

        changeRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/changeRole.png"))); // NOI18N
        changeRole.setText("Đổi vai trò");
        changeRole.setFocusable(false);
        changeRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changeRole.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        changeRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeRoleActionPerformed(evt);
            }
        });
        jToolBar1.add(changeRole);

        listAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listAccount.setRowHeight(30);
        listAccount.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listAccount);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int i_row = listAccount.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần xóa", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = listAccount.getValueAt(i_row, 0).toString();
        int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá tài khoản này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            new delete().getInstance().deleteAccountById(id);
            model.removeRow(i_row);
            JOptionPane.showMessageDialog(null, "Xóa thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        // TODO add your handling code here:
        int i_row = listAccount.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần đổi mật khẩu", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = listAccount.getValueAt(i_row, 0).toString();
        String newPassword = JOptionPane.showInputDialog(null, "Nhập mật khẩu mới:");
        if (newPassword == null) {
            // Người dùng nhấn Cancel, không làm gì cả
            return;
        }
        if (newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mật khẩu mới", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        new edit().getInstance().changePassword(id, newPassword);
        JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_changePasswordBtnActionPerformed

    private void changeStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStatusBtnActionPerformed
        // TODO add your handling code here:
        int i_row = listAccount.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần đổi trạng thái", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = listAccount.getValueAt(i_row, 0).toString();
        int luachon = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thay đổi trang thái không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (luachon == JOptionPane.YES_OPTION) {
            new edit().getInstance().changeStatus(id);
            boolean status = (boolean) listAccount.getValueAt(i_row, 4);
            model.setValueAt(!status, i_row, 4);
        }
    }//GEN-LAST:event_changeStatusBtnActionPerformed

    private void changeRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRoleActionPerformed
        // TODO add your handling code here:
        // right here
        int i_row = listAccount.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần đổi vai trò", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (model.getValueAt(i_row,3).equals("Admin")){
            JOptionPane.showMessageDialog(null, "Tài khoản này là Admin, không thể thay đổi vai trò", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id = listAccount.getValueAt(i_row, 0).toString();
        int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thay đổi vai trò không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            new edit().getInstance().changeRole(id);
            String role = (String) listAccount.getValueAt(i_row, 3);
            model.setValueAt(role.equals("Employee") ? "Manager" : "Employee", i_row, 3);
            JOptionPane.showMessageDialog(null, "Đổi vai trò thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_changeRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JButton changeRole;
    private javax.swing.JButton changeStatusBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable listAccount;
    // End of variables declaration//GEN-END:variables
}
