/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.controller.addNew;
import com.doan.controller.delete;
import com.doan.controller.generateNewId;
import com.doan.controller.search;
import com.doan.dao.HoaDonDAO;
import com.doan.dao.NhanVienDAO;
import com.doan.dao.SanPhamDAO;
import com.doan.model.HoaDon;
import com.doan.model.NhanVien;
import com.doan.model.SanPham;
import java.awt.event.KeyEvent;
import java.lang.reflect.Array;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class BillForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form BillForm
     */
    
    DefaultTableModel model;
    DefaultTableModel model2;
    DefaultTableModel model3;
    DefaultTableModel model4;
    
    public BillForm() {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.setNorthPane(null);        // Ẩn thanh tiêu đề
        }
        
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        BillTable.setModel(model);
        String [] columns = {"Mã Hóa Đơn", "Ngày Lập", "Tổng Tiền", "Nhân Viên Lập"};
        model.setColumnIdentifiers(columns);
        
        List<HoaDon> bill = new HoaDonDAO().getInstance().selectAll();
        loadTableBill(bill);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addnewBill = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JTable();
        jScroll = new javax.swing.JScrollPane();
        Item_in_Bill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdBill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdEmployee = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        quantity_added_item = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        add_new_item_Btn = new javax.swing.JButton();
        doneBtn = new javax.swing.JButton();
        editQuantityItemFormBillBtn = new javax.swing.JButton();
        deleteItemFormBilBtn = new javax.swing.JButton();
        FieldSearch = new javax.swing.JTextField();
        refesh2Btn = new javax.swing.JButton();
        detailBill = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        detailIdItem = new javax.swing.JLabel();
        detailCreatedDayBill = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        detailEmployee = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailItemInBill = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        refreshBtn = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        BillTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        AddBillBtn = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();

        addnewBill.setTitle("Tạo Hóa Đơn");
        addnewBill.setBackground(new java.awt.Color(255, 255, 255));
        addnewBill.setModal(true);
        addnewBill.setResizable(false);
        addnewBill.setSize(new java.awt.Dimension(1100, 850));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1100, 800));

        jPanel7.setBackground(new java.awt.Color(36, 16, 78));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm Hóa Đơn Mới");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        listItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listItem.setRowHeight(30);
        jScrollPane1.setViewportView(listItem);

        Item_in_Bill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Item_in_Bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Item_in_Bill.setRowHeight(30);
        jScroll.setViewportView(Item_in_Bill);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mã Hóa Đơn:");

        txtIdBill.setEditable(false);
        txtIdBill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã Nhân Viên:");

        txtIdEmployee.setEditable(false);
        txtIdEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Danh Sách Sản Phẩm");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Số Lượng");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tổng Tiền");

        txtTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalPrice.setForeground(new java.awt.Color(153, 0, 0));
        txtTotalPrice.setText("0.0đ");

        add_new_item_Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_new_item_Btn.setText("Thêm");
        add_new_item_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_item_BtnActionPerformed(evt);
            }
        });

        doneBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        doneBtn.setText("Thanh Toán");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        editQuantityItemFormBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/edit2.png"))); // NOI18N
        editQuantityItemFormBillBtn.setText("Sửa số lượng");
        editQuantityItemFormBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuantityItemFormBillBtnActionPerformed(evt);
            }
        });

        deleteItemFormBilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/delete2.png"))); // NOI18N
        deleteItemFormBilBtn.setText("Xóa sản phẩm");
        deleteItemFormBilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemFormBilBtnActionPerformed(evt);
            }
        });

        FieldSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FieldSearch.setToolTipText("Nhập tên sản phẩm để tìm kiếm");
        FieldSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));
        FieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldSearchKeyPressed(evt);
            }
        });

        refesh2Btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        refesh2Btn.setText("Làm Mới");
        refesh2Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refesh2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refesh2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(FieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(refesh2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdBill))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(73, 73, 73))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(editQuantityItemFormBillBtn)
                        .addGap(93, 93, 93)
                        .addComponent(deleteItemFormBilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addGap(69, 69, 69)
                .addComponent(quantity_added_item, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(add_new_item_Btn)
                .addGap(101, 101, 101)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneBtn)
                .addGap(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtIdBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refesh2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScroll)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editQuantityItemFormBillBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(deleteItemFormBilBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantity_added_item, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_new_item_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(doneBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addnewBillLayout = new javax.swing.GroupLayout(addnewBill.getContentPane());
        addnewBill.getContentPane().setLayout(addnewBillLayout);
        addnewBillLayout.setHorizontalGroup(
            addnewBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addnewBillLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addnewBillLayout.setVerticalGroup(
            addnewBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        detailBill.setTitle("Thông Tin Chi Tiết Hóa Đơn");
        detailBill.setModal(true);
        detailBill.setResizable(false);
        detailBill.setSize(new java.awt.Dimension(1100, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(36, 16, 78));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Chi Tiết Hóa Đơn");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(25, 25, 25))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Mã Hóa Đơn");

        detailIdItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        detailCreatedDayBill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Ngày Lập");

        detailEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nhân Viên Lập");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Danh Sách Sản Phẩm");

        detailItemInBill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        detailItemInBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        detailItemInBill.setRowHeight(30);
        jScrollPane2.setViewportView(detailItemInBill);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(detailIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(detailCreatedDayBill, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(detailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(detailCreatedDayBill, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailIdItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane2)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout detailBillLayout = new javax.swing.GroupLayout(detailBill.getContentPane());
        detailBill.getContentPane().setLayout(detailBillLayout);
        detailBillLayout.setHorizontalGroup(
            detailBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        detailBillLayout.setVerticalGroup(
            detailBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        refreshBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/refresh.png"))); // NOI18N
        refreshBtn.setText("Làm mới");
        refreshBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        dateChooser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Ngày Lập");

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/search.png"))); // NOI18N
        searchBtn.setText("Tìm Kiếm");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 6, 690, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        BillTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BillTable.setRowHeight(30);
        BillTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane.setViewportView(BillTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, -1, -1));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chỉnh Sửa"));
        jToolBar1.setRollover(true);

        AddBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/add.png"))); // NOI18N
        AddBillBtn.setText("Thêm");
        AddBillBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBillBtn.setFocusable(false);
        AddBillBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddBillBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBillBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(AddBillBtn);

        btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/view.png"))); // NOI18N
        btnDetail.setText("Xem chi tiết");
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDetail);

        jPanel2.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1088, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBillBtnActionPerformed
        // TODO add your handling code here:

        txtIdBill.setText(new generateNewId().getInstance().generateNewIdBill());

        model2 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        model3 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        listItem.setModel(model2);
        Item_in_Bill.setModel(model3);
        String[] columns1 = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Giá Niêm Yết", "Số Lượng"};
        String[] columns2 = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Giá Niêm Yết", "Số Lượng", "Thành Tiền"};
        model2.setColumnIdentifiers(columns1);
        model3.setColumnIdentifiers(columns2);

 
        List<SanPham> sp = new SanPhamDAO().getInstance().selectAll();

        
        for (SanPham x : sp) {
            if (x.getSoLuong() > 0){
                model2.addRow(new Object[]{
                    x.getMaSP(),
                    x.getTenSP(),
                    x.getGiaNY(),
                    x.getSoLuong()
                });   
            }
            
        }
        addnewBill.setLocationRelativeTo(null);
        addnewBill.setVisible(true);
    }//GEN-LAST:event_AddBillBtnActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        int i_row = BillTable.getSelectedRow();
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn hóa đơn","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = BillTable.getValueAt(i_row, 0).toString();
        HoaDon hd = new HoaDonDAO().getInstance().selectById(id);
        detailIdItem.setText(hd.getMaHD());
        detailCreatedDayBill.setText(String.valueOf(hd.getNgayLap()));
        detailEmployee.setText(hd.getNVLap().getTenNV());

        model4 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        detailItemInBill.setModel(model4);
        String columns [] ={"Mã Sản Phẩm", "Tên Sản Phẩm", "Giá", "Số Lượng", "Thành Tiền"};
        model4.setColumnIdentifiers(columns);
        model4.setRowCount(0);

        List<SanPham> sp = hd.getSP();
        for (SanPham x : sp) {
            model4.addRow(new Object[]{
                x.getMaSP(),
                x.getTenSP(),
                x.getGiaNY(),
                x.getSoLuong(),
                x.getGiaNY() * x.getSoLuong()
            });
        }
        detailBill.setLocationRelativeTo(null);
        detailBill.setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void add_new_item_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_item_BtnActionPerformed
        // TODO add your handling code here:
        int i_row = listItem.getSelectedRow();
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn sản phẩm","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int max_quantity = Integer.valueOf(listItem.getValueAt(i_row, 3).toString()); 
        if (max_quantity == 0){
            JOptionPane.showMessageDialog(null, "Sản phẩm đã hết hàng", "Cảnh Báo",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ((int) quantity_added_item.getValue() <= 0 ){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập số lượng","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if ((int) quantity_added_item.getValue() > max_quantity){
            quantity_added_item.setValue(max_quantity);
            listItem.setValueAt(0, i_row, 3);
        }
        SanPham sp = new SanPhamDAO().getInstance().selectById(listItem.getValueAt(i_row, 0).toString());
        model2.setValueAt(max_quantity - (int) quantity_added_item.getValue(), i_row, 3);
        model3.addRow(new Object[]{
            sp.getMaSP(),
            sp.getTenSP(),
            sp.getGiaNY(),
            (int) quantity_added_item.getValue(),
            (int) quantity_added_item.getValue() * sp.getGiaNY()
        });
        autoCalculate();

    }//GEN-LAST:event_add_new_item_BtnActionPerformed

    private void deleteItemFormBilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemFormBilBtnActionPerformed
        // TODO add your handling code here:
        int i_row = Item_in_Bill.getSelectedRow();
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn sản phẩm","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        for (int i=0; i<model2.getRowCount(); i++){
            if (listItem.getValueAt(i, 0).toString().equals(Item_in_Bill.getValueAt(i_row, 0).toString())){
                int max_quantity = Integer.valueOf(listItem.getValueAt(i, 3).toString());
                model2.setValueAt(max_quantity + Integer.valueOf(Item_in_Bill.getValueAt(i_row, 3).toString()), i, 3);
                break;
            }
        }
        model3.removeRow(i_row);
        autoCalculate();
    }//GEN-LAST:event_deleteItemFormBilBtnActionPerformed

    private void editQuantityItemFormBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuantityItemFormBillBtnActionPerformed
        // TODO add your handling code here:
        int i_row = Item_in_Bill.getSelectedRow();
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn sản phẩm","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int sl;
        do {
            sl = Integer.valueOf(JOptionPane.showInputDialog(null,"Vui lòng nhập số lượng sản phẩm","Sửa số lượng sản phẩm",JOptionPane.OK_OPTION));
            if (sl < 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng từ 0 trở lên", "Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            }
        } while (sl < 0);

        if (sl == 0){
            model3.removeRow(i_row);
            autoCalculate();
            return;
        }
        int max = Integer.valueOf(listItem.getValueAt(i_row, 3).toString());
        if (sl > max ){
            sl = max;
        }
        int old_quan = (int) Item_in_Bill.getValueAt(i_row, 3);
        for (int i=0; i< model2.getRowCount(); i++){
            if (listItem.getValueAt(i, 0).toString().equals(Item_in_Bill.getValueAt(i_row, 0).toString())){
                int max_quantity = Integer.valueOf(listItem.getValueAt(i, 3).toString());
                model2.setValueAt(max_quantity + old_quan - sl, i, 3);
            }
        }
        model3.setValueAt(sl, i_row, 3);
        model3.setValueAt(sl * Double.valueOf(Item_in_Bill.getValueAt(i_row, 2).toString()), i_row, 4);
        autoCalculate();
    }//GEN-LAST:event_editQuantityItemFormBillBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        // TODO add your handling code here:
        if (model3.getRowCount() == 0){
            JOptionPane.showMessageDialog(null,"Vui lòng thêm sản phẩm vào hóa đơn","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        String maHD = txtIdBill.getText().toString();
        NhanVien nv = NhanVienDAO.getInstance().selectById(txtIdEmployee.getText());
        LocalDateTime ngayLap = LocalDateTime.now();
        List<SanPham> sp = new ArrayList<SanPham>();
        for(int i = 0; i < Item_in_Bill.getRowCount(); i++){
            SanPham x = SanPhamDAO.getInstance().selectById(Item_in_Bill.getValueAt(i, 0).toString());
            SanPham y = SanPhamDAO.getInstance().selectById(Item_in_Bill.getValueAt(i, 0).toString());
            if (y != null) {
                y.setSoLuong(y.getSoLuong() - Integer.parseInt(Item_in_Bill.getValueAt(i, 3).toString()));
                SanPhamDAO.getInstance().update(y);
                x.setSoLuong(Integer.parseInt(Item_in_Bill.getValueAt(i, 3).toString()));
                sp.add(x);
            } else {
                JOptionPane.showMessageDialog(null, "Sản phẩm không tồn tại: " + Item_in_Bill.getValueAt(i, 0).toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        double tongTien = Double.parseDouble(txtTotalPrice.getText());
        addNew.getInstance().addNewBill(maHD, nv, ngayLap, sp, tongTien);
        JOptionPane.showMessageDialog(null, "Tạo hóa đơn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        addnewBill.setVisible(false);
        List<HoaDon> bill = new HoaDonDAO().getInstance().selectAll();
        model.setRowCount(0);
        for(HoaDon billItem : bill){
            model.addRow(new Object[]{
                billItem.getMaHD(),
                billItem.getNgayLap(),
                billItem.getTongTien(),
                billItem.getNVLap().getTenNV()
            });
        }
    }//GEN-LAST:event_doneBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        loadTableBill(new HoaDonDAO().getInstance().selectAll());
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        // right here
        java.util.Date selectedDate = dateChooser.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày", "Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        ArrayList<HoaDon> list = new search().getInstance().searchBill(sqlDate);
        if (list.isEmpty()){
            JOptionPane.showMessageDialog(null, "Không tìm thấy hóa đơn nào trong ngày này", "Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        loadTableBill(list);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void FieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldSearchKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyCode() == KeyEvent.VK_ENTER){
            SearchItem();
        }
    }//GEN-LAST:event_FieldSearchKeyPressed

    private void refesh2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refesh2BtnActionPerformed
        // TODO add your handling code here:
        setTableData(new SanPhamDAO().getInstance().selectAll());
    }//GEN-LAST:event_refesh2BtnActionPerformed


    public void setIdEmployee(String id){
        this.txtIdEmployee.setText(id);
    }

    public void autoCalculate(){
        double tongTien = 0;
        for(int i = 0; i < model3.getRowCount(); i++){
            tongTien += Double.valueOf(model3.getValueAt(i, 4).toString());
        }
        txtTotalPrice.setText(String.valueOf(tongTien));
    }

    public void loadTableBill(List<HoaDon> bill){
        model.setRowCount(0);
        for(HoaDon billItem : bill){
            model.addRow(new Object[]{
                billItem.getMaHD(),
                billItem.getNgayLap(),
                billItem.getTongTien(),
                billItem.getNVLap().getTenNV()
            });
        }
    }
    
    public void setTableData(ArrayList<SanPham> list){
        model2.setRowCount(0);
        for (SanPham x : list){
            if (x.getSoLuong() > 0){
                model2.addRow(new Object[]{
                    x.getMaSP(),
                    x.getTenSP(),
                    x.getGiaNY(),
                    x.getSoLuong()
                });   
            }
        }
    }
    
    private void SearchItem(){
        String key =FieldSearch.getText(); 
        if (key.equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khóa tìm kiếm");
            return;
        }
        ArrayList<SanPham> list = new search().getInstance().searchItem(key);
        if(list.size() == 0){
            JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm");
            return;
        }
        model.setRowCount(0);
        setTableData(list);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBillBtn;
    private javax.swing.JTable BillTable;
    private javax.swing.JTextField FieldSearch;
    private javax.swing.JTable Item_in_Bill;
    private javax.swing.JButton add_new_item_Btn;
    private javax.swing.JDialog addnewBill;
    private javax.swing.JButton btnDetail;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton deleteItemFormBilBtn;
    private javax.swing.JDialog detailBill;
    private javax.swing.JLabel detailCreatedDayBill;
    private javax.swing.JLabel detailEmployee;
    private javax.swing.JLabel detailIdItem;
    private javax.swing.JTable detailItemInBill;
    private javax.swing.JButton doneBtn;
    private javax.swing.JButton editQuantityItemFormBillBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScroll;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable listItem;
    private javax.swing.JSpinner quantity_added_item;
    private javax.swing.JButton refesh2Btn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtIdBill;
    private javax.swing.JTextField txtIdEmployee;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
