/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.doan.view;

import java.awt.Color;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.doan.model.TaiKhoan;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Asus
 */
public class EmployeeView extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeView
     */
    
    private TaiKhoan currAcc;
    
    Color ClickedColor = new Color(120, 73, 168);
    Color DefaultColor = new Color(36,16,78);
    
    public EmployeeView() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/doan/icon/logo.png"));
        setIconImage(icon.getImage());
        this.setLocationRelativeTo(null);
        
        ItemForm it = new ItemForm();
        
        MainContent.removeAll();
        MainContent.add(it).setVisible(true);
        it.setSize(MainContent.getWidth(),MainContent.getHeight());
        it.setLocation(0, 0);
        
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);        
    }
    
    public EmployeeView(TaiKhoan acc) {
        initComponents();
        
        this.currAcc = acc;
        this.setLocationRelativeTo(null);
        
        ItemForm it = new ItemForm();
        
        MainContent.removeAll();
        MainContent.add(it).setVisible(true);
        it.setSize(MainContent.getWidth(),MainContent.getHeight());
        it.setLocation(0, 0);
        
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        MainContent = new javax.swing.JPanel();
        NavbarMenu = new javax.swing.JPanel();
        TenTaiKhoan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        HoaDon = new javax.swing.JPanel();
        BillBtn = new javax.swing.JLabel();
        ImportBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PhieuNhap = new javax.swing.JPanel();
        GrnBtn = new javax.swing.JLabel();
        NhaCungCap = new javax.swing.JPanel();
        SuplierBtn = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SanPham = new javax.swing.JPanel();
        ProductBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao diện Nhân Viên");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainContent.setBackground(new java.awt.Color(255, 255, 255));
        MainContent.setPreferredSize(new java.awt.Dimension(1100, 800));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        NavbarMenu.setBackground(new java.awt.Color(36, 16, 78));

        TenTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TenTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        TenTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TenTaiKhoan.setText("WELCOME");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/employees2.png"))); // NOI18N

        HoaDon.setBackground(new java.awt.Color(36, 16, 78));
        HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDonMousePressed(evt);
            }
        });

        BillBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BillBtn.setForeground(new java.awt.Color(255, 255, 255));
        BillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/invoice.png"))); // NOI18N
        BillBtn.setText("Hóa Đơn");

        javax.swing.GroupLayout HoaDonLayout = new javax.swing.GroupLayout(HoaDon);
        HoaDon.setLayout(HoaDonLayout);
        HoaDonLayout.setHorizontalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BillBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HoaDonLayout.setVerticalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BillBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        ImportBtn.setBackground(new java.awt.Color(36, 16, 78));
        ImportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ImportBtnMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/import.png"))); // NOI18N
        jLabel5.setText("Nhập Hàng");

        javax.swing.GroupLayout ImportBtnLayout = new javax.swing.GroupLayout(ImportBtn);
        ImportBtn.setLayout(ImportBtnLayout);
        ImportBtnLayout.setHorizontalGroup(
            ImportBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImportBtnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ImportBtnLayout.setVerticalGroup(
            ImportBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PhieuNhap.setBackground(new java.awt.Color(36, 16, 78));
        PhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhieuNhapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhieuNhapMousePressed(evt);
            }
        });

        GrnBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        GrnBtn.setForeground(new java.awt.Color(255, 255, 255));
        GrnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/grn.png"))); // NOI18N
        GrnBtn.setText("Phiếu Nhập");

        javax.swing.GroupLayout PhieuNhapLayout = new javax.swing.GroupLayout(PhieuNhap);
        PhieuNhap.setLayout(PhieuNhapLayout);
        PhieuNhapLayout.setHorizontalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuNhapLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(GrnBtn)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PhieuNhapLayout.setVerticalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GrnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        NhaCungCap.setBackground(new java.awt.Color(36, 16, 78));
        NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhaCungCapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhaCungCapMousePressed(evt);
            }
        });

        SuplierBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SuplierBtn.setForeground(new java.awt.Color(255, 255, 255));
        SuplierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/supplier.png"))); // NOI18N
        SuplierBtn.setText("Nhà Cung Cấp");
        SuplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuplierBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout NhaCungCapLayout = new javax.swing.GroupLayout(NhaCungCap);
        NhaCungCap.setLayout(NhaCungCapLayout);
        NhaCungCapLayout.setHorizontalGroup(
            NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaCungCapLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(SuplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        NhaCungCapLayout.setVerticalGroup(
            NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Logout.setBackground(new java.awt.Color(36, 16, 78));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/logout.png"))); // NOI18N
        LogoutBtn.setText("Đăng Xuất");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LogoutBtn)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        SanPham.setBackground(new java.awt.Color(36, 16, 78));
        SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanPhamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SanPhamMousePressed(evt);
            }
        });

        ProductBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ProductBtn.setForeground(new java.awt.Color(255, 255, 255));
        ProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/dairy-products.png"))); // NOI18N
        ProductBtn.setText("Sản Phẩm");

        javax.swing.GroupLayout SanPhamLayout = new javax.swing.GroupLayout(SanPham);
        SanPham.setLayout(SanPhamLayout);
        SanPhamLayout.setHorizontalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ProductBtn)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        SanPhamLayout.setVerticalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SanPhamLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(ProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout NavbarMenuLayout = new javax.swing.GroupLayout(NavbarMenu);
        NavbarMenu.setLayout(NavbarMenuLayout);
        NavbarMenuLayout.setHorizontalGroup(
            NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarMenuLayout.createSequentialGroup()
                .addGroup(NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(NavbarMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarMenuLayout.createSequentialGroup()
                        .addComponent(NhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(HoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NavbarMenuLayout.createSequentialGroup()
                                .addComponent(PhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGroup(NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NavbarMenuLayout.setVerticalGroup(
            NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TenTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ImportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(NavbarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NavbarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(MainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseClicked
        // TODO add your handling code here:
        BillForm bill = new BillForm();
        bill.setIdEmployee(currAcc.getNhanVien().getMaNV());
        MainContent.removeAll();
        MainContent.add(bill).setVisible(true);
        bill.setSize(MainContent.getWidth(),MainContent.getHeight());
        bill.setLocation(0, 0);

    }//GEN-LAST:event_HoaDonMouseClicked

    private void HoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(ClickedColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
    }//GEN-LAST:event_HoaDonMousePressed

    private void ImportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportBtnMouseClicked
        // TODO add your handling code here:
        ImportForm imp = new ImportForm();
        imp.setIdEmployee(currAcc.getNhanVien().getMaNV());
        MainContent.removeAll();
        MainContent.add(imp).setVisible(true);
        imp.setSize(MainContent.getWidth(),MainContent.getHeight());
        imp.setLocation(0, 0);
    }//GEN-LAST:event_ImportBtnMouseClicked

    private void ImportBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportBtnMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(ClickedColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
    }//GEN-LAST:event_ImportBtnMousePressed

    private void PhieuNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuNhapMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(ClickedColor);
    }//GEN-LAST:event_PhieuNhapMousePressed

    private void SuplierBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuplierBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuplierBtnMousePressed

    private void NhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaCungCapMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(ClickedColor);
        PhieuNhap.setBackground(DefaultColor);
    }//GEN-LAST:event_NhaCungCapMousePressed

    private void NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaCungCapMouseClicked
        // TODO add your handling code here:
        SupplierForm sup = new SupplierForm();
        MainContent.removeAll();
        MainContent.add(sup).setVisible(true);
        sup.setSize(MainContent.getWidth(),MainContent.getHeight());
        sup.setLocation(0, 0);
    }//GEN-LAST:event_NhaCungCapMouseClicked

    private void PhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuNhapMouseClicked
        // TODO add your handling code here:
        GrnForm grn = new GrnForm();
        MainContent.removeAll();
        MainContent.add(grn).setVisible(true);
        grn.setSize(MainContent.getWidth(),MainContent.getHeight());
        grn.setLocation(0, 0);
    }//GEN-LAST:event_PhieuNhapMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        int relly = JOptionPane.showConfirmDialog(null,"Bạn muốn thoát khỏi chương trình ?","Xác Nhận",JOptionPane.YES_NO_OPTION);
        if (relly == JOptionPane.YES_OPTION) {
            this.dispose();
            LoginForm a = new LoginForm();
            a.setVisible(true);
        }
    }//GEN-LAST:event_LogoutMouseClicked

    private void SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMouseClicked
        // TODO add your handling code here:
        ItemForm it = new ItemForm();
        MainContent.removeAll();
        MainContent.add(it).setVisible(true);
        it.setSize(MainContent.getWidth(),MainContent.getHeight());
        it.setLocation(0, 0);
    }//GEN-LAST:event_SanPhamMouseClicked

    private void SanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        
    }//GEN-LAST:event_SanPhamMousePressed

    
    public void setName(String name){
        this.TenTaiKhoan.setText(name);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Set FlatLaf LookAndFeel
                    UIManager.setLookAndFeel(new FlatLightLaf());
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                new EmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BillBtn;
    private javax.swing.JLabel GrnBtn;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JPanel ImportBtn;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel LogoutBtn;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel NavbarMenu;
    private javax.swing.JPanel NhaCungCap;
    private javax.swing.JPanel PhieuNhap;
    private javax.swing.JLabel ProductBtn;
    private javax.swing.JPanel SanPham;
    private javax.swing.JLabel SuplierBtn;
    private javax.swing.JLabel TenTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
