/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.controller.addNew;
import com.doan.controller.generateNewId;
import com.doan.controller.search;
import com.doan.dao.NCCDAO;
import com.doan.dao.NhanVienDAO;
import com.doan.dao.SanPhamDAO;
import com.doan.model.NCC;
import com.doan.model.NhanVien;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;
import java.sql.Date;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import com.doan.model.SanPham;
import com.sun.jdi.IntegerType;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class ImportForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ImportForm
     */
    DefaultTableModel model;
    DefaultTableModel model2;
    
    public ImportForm() {
        initComponents();
        
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.setNorthPane(null);        // Ẩn thanh tiêu đề
        }
        
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        model2 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        productTable.setModel(model);
        bangNhap.setModel(model2);
        String [] columns = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá Bán"};
        String [] columns2 = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá Nhập", "Thành Tiền"};
        model.setColumnIdentifiers(columns);
        model2.setColumnIdentifiers(columns2);
        
        List<SanPham> sp = new SanPhamDAO().getInstance().selectAll() ;
        for (SanPham x : sp){
            model.addRow(new Object[]{
                x.getMaSP(),
                x.getTenSP(),
                x.getSoLuong(),
                x.getGiaNY()
            });
        }

        txtIdGrn.setText(new generateNewId().getInstance().generateNewIdGrnBill());
        List<NCC> nccList = new NCCDAO().getInstance().selectAll();
        for (NCC x : nccList){
            listSupplier.addItem(x.getTenNCC());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capnhat = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameItem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        createdDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ExpiredDay = new javax.swing.JTextField();
        OkBtn = new javax.swing.JButton();
        addItem = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtIdProduct = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPriceProduct = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtQuantityProduct = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        txtNameProduct = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLoaiSanPham = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtImportPriceProduct = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchBox = new javax.swing.JTextField();
        refreshBtn = new javax.swing.JButton();
        addNewItemBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        bangNhap = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        txtIdGrn = new javax.swing.JLabel();
        listSupplier = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        quantity_added_item = new javax.swing.JSpinner();
        add_new_item_Btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        ImportBtn = new javax.swing.JButton();
        editQuantityItemFormGrnBtn = new javax.swing.JButton();
        deleteItemFormGrnBtn = new javax.swing.JButton();
        editPriceItemFormGrnBtn = new javax.swing.JButton();
        txtIdImportEmployee = new javax.swing.JLabel();

        capnhat.setModal(true);
        capnhat.setResizable(false);
        capnhat.setSize(new java.awt.Dimension(420, 340));

        jPanel5.setBackground(new java.awt.Color(36, 16, 78));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cập Nhật Ngày Sản Xuất và Hạn Sử Dụng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sản Phẩm:");

        nameItem.setEditable(false);
        nameItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("NSX:");

        createdDay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        createdDay.setToolTipText("YYYY-MM-DD");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("HSD:");

        ExpiredDay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ExpiredDay.setToolTipText("YYYY-MM-DD");

        OkBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OkBtn.setText("OK");
        OkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameItem)
                    .addComponent(createdDay)
                    .addComponent(ExpiredDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OkBtn)
                .addGap(163, 163, 163))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameItem, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createdDay, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExpiredDay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(OkBtn)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout capnhatLayout = new javax.swing.GroupLayout(capnhat.getContentPane());
        capnhat.getContentPane().setLayout(capnhatLayout);
        capnhatLayout.setHorizontalGroup(
            capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        capnhatLayout.setVerticalGroup(
            capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addItem.setTitle("Thêm Sản Phẩm Mới");
        addItem.setBackground(new java.awt.Color(255, 255, 255));
        addItem.setModal(true);
        addItem.setResizable(false);
        addItem.setSize(new java.awt.Dimension(800, 520));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(36, 16, 78));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Thêm Sản Phẩm Mới");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        txtIdProduct.setEditable(false);
        txtIdProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Mã sản phẩm");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Tên sản phẩm");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Giá Niên Yết");

        txtPriceProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Số lượng");

        txtQuantityProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cancelBtn.setBackground(new java.awt.Color(255, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Hủy bỏ");
        cancelBtn.setBorder(null);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 153, 51));
        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Thêm");
        addBtn.setBorder(null);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        txtNameProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Loại sản phẩm");

        txtLoaiSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồ ăn", "Đồ Uống", "Đồ gia dụng" }));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Giá Nhập");

        txtImportPriceProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIdProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPriceProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(txtQuantityProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(txtImportPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtLoaiSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(txtPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(5, 5, 5)
                        .addComponent(txtImportPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(txtQuantityProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout addItemLayout = new javax.swing.GroupLayout(addItem.getContentPane());
        addItem.getContentPane().setLayout(addItemLayout);
        addItemLayout.setHorizontalGroup(
            addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addItemLayout.setVerticalGroup(
            addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        searchBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchBox.setToolTipText("Nhập tên sản phẩm để tìm kiếm");
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });
        searchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBoxKeyReleased(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/refresh.png"))); // NOI18N
        refreshBtn.setText("Làm mới");
        refreshBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        addNewItemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/plus.png"))); // NOI18N
        addNewItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addNewItemBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewItemBtn))
                .addGap(27, 27, 27))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        productTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá"
            }
        ));
        productTable.setRowHeight(30);
        productTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(productTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã Phiếu Nhập:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nhà Cung Cấp:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mã Nhân Viên:");

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));

        bangNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bangNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số Lượng", "Đơn Giá"
            }
        ));
        bangNhap.setRowHeight(30);
        bangNhap.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(bangNhap);

        txtIdGrn.setBackground(new java.awt.Color(204, 204, 204));
        txtIdGrn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtIdGrn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listSupplier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Số Lượng");

        add_new_item_Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_new_item_Btn.setText("Thêm");
        add_new_item_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_item_BtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tổng Tiền");

        txtTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalPrice.setForeground(new java.awt.Color(153, 0, 0));
        txtTotalPrice.setText("0.0đ");

        ImportBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ImportBtn.setText("Nhập Hàng");
        ImportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(69, 69, 69)
                .addComponent(quantity_added_item, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(add_new_item_Btn)
                .addGap(124, 124, 124)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImportBtn)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantity_added_item, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_new_item_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalPrice)
                    .addComponent(ImportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        editQuantityItemFormGrnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/edit2.png"))); // NOI18N
        editQuantityItemFormGrnBtn.setText("Sửa số lượng");
        editQuantityItemFormGrnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuantityItemFormGrnBtnActionPerformed(evt);
            }
        });

        deleteItemFormGrnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/delete2.png"))); // NOI18N
        deleteItemFormGrnBtn.setText("Xóa sản phẩm");
        deleteItemFormGrnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemFormGrnBtnActionPerformed(evt);
            }
        });

        editPriceItemFormGrnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/edit3.png"))); // NOI18N
        editPriceItemFormGrnBtn.setText("Sửa giá nhập");
        editPriceItemFormGrnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPriceItemFormGrnBtnActionPerformed(evt);
            }
        });

        txtIdImportEmployee.setBackground(new java.awt.Color(204, 204, 204));
        txtIdImportEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdImportEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(editQuantityItemFormGrnBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editPriceItemFormGrnBtn)
                                        .addGap(31, 31, 31)
                                        .addComponent(deleteItemFormGrnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(157, 157, 157))
                                            .addComponent(listSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtIdImportEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIdGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtIdGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(listSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtIdImportEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editQuantityItemFormGrnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPriceItemFormGrnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteItemFormGrnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        searchBox.setText("");
        model.setRowCount(0);
        List<SanPham> sp = new SanPhamDAO().getInstance().selectAll();
        for (SanPham x : sp){
            model.addRow(new Object[]{
                x.getMaSP(),
                x.getTenSP(),
                x.getSoLuong(),
                x.getGiaNY()
            });
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxKeyReleased

    private void searchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyPressed
        // TODO add your handling code here:
        //right here
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String key = searchBox.getText();
            if (key.equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên sản phẩm cần tìm","Cảnh Báo",JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                ArrayList<SanPham> list = new search().getInstance().searchItem(key);
                if(list.size() == 0){
                    JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm");
                    return;
                }
                model.setRowCount(0);
                for (SanPham x : list){
                    model.addRow(new Object[]{
                        x.getMaSP(),
                        x.getTenSP(),
                        x.getSoLuong(),
                        x.getGiaNY()
                    });
                }
            }
        }
    }//GEN-LAST:event_searchBoxKeyPressed

    private void add_new_item_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_item_BtnActionPerformed
        // TODO add your handling code here:
        int i_row = productTable.getSelectedRow();
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn sản phẩm","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if ((int) quantity_added_item.getValue() <= 0 ){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập số lượng","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        SanPham sp = new SanPhamDAO().getInstance().selectById(productTable.getValueAt(i_row, 0).toString());
        model2.addRow(new Object[]{
            sp.getMaSP(),
            sp.getTenSP(),
            (int) quantity_added_item.getValue(),
            sp.getGiaNhap(),
            (int) quantity_added_item.getValue() * sp.getGiaNhap()
        });
        autoCalculate();
    }//GEN-LAST:event_add_new_item_BtnActionPerformed

    private void ImportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportBtnActionPerformed
        // TODO add your handling code here:
        String maPhieuNhap = txtIdGrn.getText().toString();
        NCC ncc = NCCDAO.getInstance().selectByTenNCC(listSupplier.getSelectedItem().toString());
        NhanVien nv = NhanVienDAO.getInstance().selectById(txtIdImportEmployee.getText().toString());
        Date ngayNhap = Date.valueOf(LocalDate.now());
        List<SanPham> sp = new ArrayList<SanPham>();
        for (int i = 0; i < model2.getRowCount(); i++){
            SanPham x = new SanPhamDAO().getInstance().selectById(model2.getValueAt(i, 0).toString());
            String newIdItem = new generateNewId().getInstance().generateNewIdItem();
            x.setMaSP(newIdItem);
            x.setGiaNhap(Double.valueOf(model2.getValueAt(i, 3).toString()));
            x.setSoLuong(Integer.valueOf(model2.getValueAt(i, 2).toString()));

            nameItem.setText(x.getTenSP());
            capnhat.setLocationRelativeTo(null);
            capnhat.setVisible(true);  
  
            x.setNSX(Date.valueOf(createdDay.getText().toString()));
            x.setHSD(Date.valueOf(ExpiredDay.getText().toString()));

            if (x.getNSX().after(x.getHSD())){
                JOptionPane.showMessageDialog(null, "Ngày sản xuất không được lớn hơn ngày hết hạn", "Cảnh Báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            sp.add(x);
            new SanPhamDAO().getInstance().insert(x);
        }
        double tongTien = Double.valueOf(txtTotalPrice.getText().toString());
        addNew.getInstance().addNewGrn(maPhieuNhap, ncc, nv, ngayNhap, sp, tongTien);
        JOptionPane.showMessageDialog(null, "Thêm hàng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        
        model.setRowCount(0);
        model2.setRowCount(0);

        for (SanPham x : new SanPhamDAO().getInstance().selectAll()) {
            model.addRow(new Object[]{
                x.getMaSP(),
                x.getTenSP(),
                x.getSoLuong(),
                x.getGiaNY()
            });
        }
    }//GEN-LAST:event_ImportBtnActionPerformed

    private void editQuantityItemFormGrnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuantityItemFormGrnBtnActionPerformed
        // TODO add your handling code here:
        int i_row = bangNhap.getSelectedRow();
        
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn sản phẩm","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int sl;
        do {
            sl = Integer.valueOf(JOptionPane.showInputDialog(null,"Vui lòng nhập số lượng sản phẩm","Sửa số lượng sản phẩm",JOptionPane.OK_OPTION));
            if (sl < 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng từ 0 trở lên", "Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            }
        } while (sl < 0);

        if (sl == 0){
            model2.removeRow(i_row);
            autoCalculate();
            return;
        }
        
        bangNhap.setValueAt(sl, i_row, 2);
        bangNhap.setValueAt(sl * Double.valueOf(bangNhap.getValueAt(i_row, 3).toString()), i_row, 4);
        autoCalculate();
        
    }//GEN-LAST:event_editQuantityItemFormGrnBtnActionPerformed

    private void deleteItemFormGrnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemFormGrnBtnActionPerformed
        // TODO add your handling code here:
        int i_row = bangNhap.getSelectedRow();
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn sản phẩm","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        model2.removeRow(i_row);
        autoCalculate();
        
    }//GEN-LAST:event_deleteItemFormGrnBtnActionPerformed

    private void editPriceItemFormGrnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPriceItemFormGrnBtnActionPerformed
        // TODO add your handling code here:
        int i_row = bangNhap.getSelectedRow();
        
        if (i_row == -1){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn sản phẩm","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        double price;
        do {
            price = Double.valueOf(JOptionPane.showInputDialog(null,"Vui lòng nhập giá nhập sản phẩm","Sửa số lượng sản phẩm",JOptionPane.OK_OPTION));
            if (price < 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập giá nhập lớn hơn 0", "Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            }
        } while (price < 0);
        
        bangNhap.setValueAt(price, i_row, 3);
        bangNhap.setValueAt(price * Integer.valueOf(bangNhap.getValueAt(i_row, 2).toString()), i_row, 4);
        autoCalculate();
    }//GEN-LAST:event_editPriceItemFormGrnBtnActionPerformed

    private void OkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBtnActionPerformed
        // TODO add your handling code here:
        capnhat.setVisible(false);
    }//GEN-LAST:event_OkBtnActionPerformed

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        txtNameProduct.setText("");
        txtPriceProduct.setText("");
        txtImportPriceProduct.setText("");
        txtQuantityProduct.setText("");
        addItem.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String id = txtIdProduct.getText();
        String nameItem = txtNameProduct.getText();
        double price = Double.valueOf((txtPriceProduct.getText()));
        double importPrice = Double.valueOf((txtImportPriceProduct.getText()));
        int quantity = Integer.valueOf(txtQuantityProduct.getText());
        String type = String.valueOf(txtLoaiSanPham.getSelectedItem());

        SanPham sp = new SanPham(id, nameItem, price, importPrice, quantity, Date.valueOf(LocalDate.now()), Date.valueOf(LocalDate.now()), type);
        for(int i = 0; i < model2.getRowCount(); i++){
            if (model2.getValueAt(i, 0).toString().equals(id)){
                Integer number = Integer.valueOf(id.substring(2)) + 1;
                id = "SP" + number.toString();
            }
        }
        model2.addRow(new Object[]{
            id,
            nameItem,
            quantity,
            importPrice,
            quantity * importPrice
        });
        addItem.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void addNewItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewItemBtnActionPerformed
        // TODO add your handling code here:
        txtIdProduct.setText(new generateNewId().getInstance().generateNewIdItem());
        addItem.setLocationRelativeTo(null);
        addItem.setVisible(true);
    }//GEN-LAST:event_addNewItemBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void setIdEmployee(String id){
        this.txtIdImportEmployee.setText(id);
    }

    

    public void autoCalculate(){
        double totalPrice = 0;
        for (int i = 0; i < model2.getRowCount(); i++) {
            totalPrice += (double) model2.getValueAt(i, 4);
        }
        txtTotalPrice.setText(String.valueOf(totalPrice));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExpiredDay;
    private javax.swing.JButton ImportBtn;
    private javax.swing.JButton OkBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JDialog addItem;
    private javax.swing.JButton addNewItemBtn;
    private javax.swing.JButton add_new_item_Btn;
    private javax.swing.JTable bangNhap;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JDialog capnhat;
    private javax.swing.JTextField createdDay;
    private javax.swing.JButton deleteItemFormGrnBtn;
    private javax.swing.JButton editPriceItemFormGrnBtn;
    private javax.swing.JButton editQuantityItemFormGrnBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> listSupplier;
    private javax.swing.JTextField nameItem;
    private javax.swing.JTable productTable;
    private javax.swing.JSpinner quantity_added_item;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField searchBox;
    private javax.swing.JLabel txtIdGrn;
    private javax.swing.JLabel txtIdImportEmployee;
    private javax.swing.JTextField txtIdProduct;
    private javax.swing.JTextField txtImportPriceProduct;
    private javax.swing.JComboBox<String> txtLoaiSanPham;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtPriceProduct;
    private javax.swing.JTextField txtQuantityProduct;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
