/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.doan.view;

import java.awt.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.doan.model.TaiKhoan;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Asus
 */
public class ManagerView extends javax.swing.JFrame {
    
    Color ClickedColor = new Color(120, 73, 168);
    Color DefaultColor = new Color(36,16,78);

    /**
     * Creates new form ManagerView
     */
    private TaiKhoan currAcc;
    
    public ManagerView(TaiKhoan acc) {
        initComponents();

        ImageIcon icon = new ImageIcon(getClass().getResource("/com/doan/icon/logo.png"));
        setIconImage(icon.getImage());
        
        this.currAcc = acc;
        this.setLocationRelativeTo(null);
        
        ItemForm it = new ItemForm();
        
        MainContent.removeAll();
        MainContent.add(it).setVisible(true);
        it.setSize(MainContent.getWidth(),MainContent.getHeight());
        it.setLocation(0, 0);
        
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }
    
    public ManagerView() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        ItemForm it = new ItemForm();
        
        MainContent.removeAll();
        MainContent.add(it).setVisible(true);
        it.setSize(MainContent.getWidth(),MainContent.getHeight());
        it.setLocation(0, 0);
        
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        NavbarMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TenTaiKhoan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        HoaDon = new javax.swing.JPanel();
        BillBtn = new javax.swing.JLabel();
        SanPham = new javax.swing.JPanel();
        ProductBtn = new javax.swing.JLabel();
        ImportBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PhieuNhap = new javax.swing.JPanel();
        GrnBtn = new javax.swing.JLabel();
        NhaCungCap = new javax.swing.JPanel();
        SuplierBtn = new javax.swing.JLabel();
        NhanVien = new javax.swing.JPanel();
        EmployeeBtn = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JLabel();
        BaoCao = new javax.swing.JPanel();
        ReportBtn = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JPanel();
        accountBtn = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao diện Quản Lý");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NavbarMenu.setBackground(new java.awt.Color(36, 16, 78));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/profile.png"))); // NOI18N

        TenTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TenTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        TenTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TenTaiKhoan.setText("WELCOME");

        HoaDon.setBackground(new java.awt.Color(36, 16, 78));
        HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDonMousePressed(evt);
            }
        });

        BillBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BillBtn.setForeground(new java.awt.Color(255, 255, 255));
        BillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/invoice.png"))); // NOI18N
        BillBtn.setText("Hóa Đơn");

        javax.swing.GroupLayout HoaDonLayout = new javax.swing.GroupLayout(HoaDon);
        HoaDon.setLayout(HoaDonLayout);
        HoaDonLayout.setHorizontalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BillBtn)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        HoaDonLayout.setVerticalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BillBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        SanPham.setBackground(new java.awt.Color(36, 16, 78));
        SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanPhamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SanPhamMousePressed(evt);
            }
        });

        ProductBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ProductBtn.setForeground(new java.awt.Color(255, 255, 255));
        ProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/dairy-products.png"))); // NOI18N
        ProductBtn.setText("Sản Phẩm");

        javax.swing.GroupLayout SanPhamLayout = new javax.swing.GroupLayout(SanPham);
        SanPham.setLayout(SanPhamLayout);
        SanPhamLayout.setHorizontalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ProductBtn)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        SanPhamLayout.setVerticalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SanPhamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ImportBtn.setBackground(new java.awt.Color(36, 16, 78));
        ImportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ImportBtnMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/import.png"))); // NOI18N
        jLabel5.setText("Nhập Hàng");

        javax.swing.GroupLayout ImportBtnLayout = new javax.swing.GroupLayout(ImportBtn);
        ImportBtn.setLayout(ImportBtnLayout);
        ImportBtnLayout.setHorizontalGroup(
            ImportBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImportBtnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        ImportBtnLayout.setVerticalGroup(
            ImportBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PhieuNhap.setBackground(new java.awt.Color(36, 16, 78));
        PhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhieuNhapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhieuNhapMousePressed(evt);
            }
        });

        GrnBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        GrnBtn.setForeground(new java.awt.Color(255, 255, 255));
        GrnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/grn.png"))); // NOI18N
        GrnBtn.setText("Phiếu Nhập");

        javax.swing.GroupLayout PhieuNhapLayout = new javax.swing.GroupLayout(PhieuNhap);
        PhieuNhap.setLayout(PhieuNhapLayout);
        PhieuNhapLayout.setHorizontalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuNhapLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(GrnBtn)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        PhieuNhapLayout.setVerticalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GrnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        NhaCungCap.setBackground(new java.awt.Color(36, 16, 78));
        NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhaCungCapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhaCungCapMousePressed(evt);
            }
        });

        SuplierBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SuplierBtn.setForeground(new java.awt.Color(255, 255, 255));
        SuplierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/supplier.png"))); // NOI18N
        SuplierBtn.setText("Nhà Cung Cấp");
        SuplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuplierBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout NhaCungCapLayout = new javax.swing.GroupLayout(NhaCungCap);
        NhaCungCap.setLayout(NhaCungCapLayout);
        NhaCungCapLayout.setHorizontalGroup(
            NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaCungCapLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(SuplierBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        NhaCungCapLayout.setVerticalGroup(
            NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        NhanVien.setBackground(new java.awt.Color(36, 16, 78));
        NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhanVienMousePressed(evt);
            }
        });

        EmployeeBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmployeeBtn.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/employees.png"))); // NOI18N
        EmployeeBtn.setText("Nhân Viên");

        javax.swing.GroupLayout NhanVienLayout = new javax.swing.GroupLayout(NhanVien);
        NhanVien.setLayout(NhanVienLayout);
        NhanVienLayout.setHorizontalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(EmployeeBtn)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        NhanVienLayout.setVerticalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        Logout.setBackground(new java.awt.Color(36, 16, 78));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/logout.png"))); // NOI18N
        LogoutBtn.setText("Đăng Xuất");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LogoutBtn)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        BaoCao.setBackground(new java.awt.Color(36, 16, 78));
        BaoCao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaoCaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BaoCaoMousePressed(evt);
            }
        });

        ReportBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/report.png"))); // NOI18N
        ReportBtn.setText("Báo Cáo");

        javax.swing.GroupLayout BaoCaoLayout = new javax.swing.GroupLayout(BaoCao);
        BaoCao.setLayout(BaoCaoLayout);
        BaoCaoLayout.setHorizontalGroup(
            BaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ReportBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BaoCaoLayout.setVerticalGroup(
            BaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        TaiKhoan.setBackground(new java.awt.Color(36, 16, 78));
        TaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaiKhoanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaiKhoanMousePressed(evt);
            }
        });

        accountBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountBtn.setForeground(new java.awt.Color(255, 255, 255));
        accountBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/account.png"))); // NOI18N
        accountBtn.setText("Tài Khoản");

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(accountBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout NavbarMenuLayout = new javax.swing.GroupLayout(NavbarMenu);
        NavbarMenu.setLayout(NavbarMenuLayout);
        NavbarMenuLayout.setHorizontalGroup(
            NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarMenuLayout.createSequentialGroup()
                .addGroup(NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ImportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(NhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(NavbarMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavbarMenuLayout.createSequentialGroup()
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NavbarMenuLayout.setVerticalGroup(
            NavbarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(TenTaiKhoan)
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ImportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(NavbarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavbarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseClicked
        // TODO add your handling code here:
        BillForm bill = new BillForm();
        bill.setIdEmployee(currAcc.getNhanVien().getMaNV());
        MainContent.removeAll();
        MainContent.add(bill).setVisible(true);
        bill.setSize(MainContent.getWidth(),MainContent.getHeight());
        bill.setLocation(0, 0);
    }//GEN-LAST:event_HoaDonMouseClicked

    private void HoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(ClickedColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_HoaDonMousePressed

    private void SanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_SanPhamMousePressed

    private void ImportBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportBtnMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(ClickedColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_ImportBtnMousePressed

    private void SuplierBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuplierBtnMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(ClickedColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_SuplierBtnMousePressed

    private void NhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaCungCapMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(ClickedColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_NhaCungCapMousePressed

    private void PhieuNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuNhapMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(ClickedColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_PhieuNhapMousePressed

    private void NhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(ClickedColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_NhanVienMousePressed

    private void SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMouseClicked
        // TODO add your handling code here:
        ItemForm it = new ItemForm();
        MainContent.removeAll();
        MainContent.add(it).setVisible(true);
        it.setSize(MainContent.getWidth(),MainContent.getHeight());
        it.setLocation(0, 0);
    }//GEN-LAST:event_SanPhamMouseClicked

    private void ImportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportBtnMouseClicked
        // TODO add your handling code here:
        ImportForm imp = new ImportForm();
        imp.setIdEmployee(currAcc.getNhanVien().getMaNV());
        MainContent.removeAll();
        MainContent.add(imp).setVisible(true);
        imp.setSize(MainContent.getWidth(),MainContent.getHeight());
        imp.setLocation(0, 0);
    }//GEN-LAST:event_ImportBtnMouseClicked

    private void NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaCungCapMouseClicked
        // TODO add your handling code here:
        SupplierForm sup = new SupplierForm();
        MainContent.removeAll();
        MainContent.add(sup).setVisible(true);
        sup.setSize(MainContent.getWidth(),MainContent.getHeight());
        sup.setLocation(0, 0);
    }//GEN-LAST:event_NhaCungCapMouseClicked

    private void NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMouseClicked
        // TODO add your handling code here:
        emInfoForm em = new emInfoForm();
        MainContent.removeAll();
        MainContent.add(em).setVisible(true);
        em.setSize(MainContent.getWidth(),MainContent.getHeight());
        em.setLocation(0, 0);
    }//GEN-LAST:event_NhanVienMouseClicked

    private void PhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuNhapMouseClicked
        // TODO add your handling code here:
        GrnForm grn = new GrnForm();
        MainContent.removeAll();
        MainContent.add(grn).setVisible(true);
        grn.setSize(MainContent.getWidth(),MainContent.getHeight());
        grn.setLocation(0, 0);
    }//GEN-LAST:event_PhieuNhapMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        int relly = JOptionPane.showConfirmDialog(null,"Bạn muốn thoát khỏi chương trình ?","Xác Nhận",JOptionPane.YES_NO_OPTION);
        if (relly == JOptionPane.YES_OPTION) {
            this.dispose();
            LoginForm a = new LoginForm();
            a.setVisible(true);
        }
    }//GEN-LAST:event_LogoutMouseClicked

    private void BaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoMouseClicked
        // TODO add your handling code here:
        ReportForm re = new ReportForm();
        MainContent.removeAll();
        MainContent.add(re).setVisible(true);
        re.setSize(MainContent.getWidth(), MainContent.getHeight());
        re.setLocation(0, 0);
    }//GEN-LAST:event_BaoCaoMouseClicked

    private void BaoCaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(ClickedColor);
        TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_BaoCaoMousePressed

    private void TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMouseClicked
        // TODO add your handling code here:
        AccountForm acc = new AccountForm();
        MainContent.removeAll();
        MainContent.add(acc).setVisible(true);
        acc.setSize(MainContent.getWidth(), MainContent.getHeight());
        acc.setLocation(0, 0);
    }//GEN-LAST:event_TaiKhoanMouseClicked

    private void TaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMousePressed
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        ImportBtn.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        BaoCao.setBackground(DefaultColor);
        TaiKhoan.setBackground(ClickedColor);
    }//GEN-LAST:event_TaiKhoanMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Set FlatLaf LookAndFeel
                    UIManager.setLookAndFeel(new FlatLightLaf());
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                new ManagerView().setVisible(true);
            }
        });
    }
    
    public void setName(String name){
        this.TenTaiKhoan.setText(name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BaoCao;
    private javax.swing.JLabel BillBtn;
    private javax.swing.JLabel EmployeeBtn;
    private javax.swing.JLabel GrnBtn;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JPanel ImportBtn;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel LogoutBtn;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel NavbarMenu;
    private javax.swing.JPanel NhaCungCap;
    private javax.swing.JPanel NhanVien;
    private javax.swing.JPanel PhieuNhap;
    private javax.swing.JLabel ProductBtn;
    private javax.swing.JLabel ReportBtn;
    private javax.swing.JPanel SanPham;
    private javax.swing.JLabel SuplierBtn;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JLabel TenTaiKhoan;
    private javax.swing.JLabel accountBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}

